### ISSUE TITLE
Crashes on launch with Provi's Health Bars

### ISSUE THREAD

**Issue by Poopooracoocoo** [IMB11/SkinShuffle#56]
### Describe the issue

Prism Launcher 7.2
Fabric Loader 0.15.3
Minecraft 1.20.2
Fabric API 0.91.2+1.20.2
Skin Shuffle 1.0.2+1.20.2
Provi's Health Bars 1.2.2+1.20.2

Crashes on launch with Provi's Health Bars

### Relevant log output

https://mclo.gs/RfxckeX

### SkinShuffle version

1.0.2+1.20.2

### Crash report

[crash-2023-12-28_12.40.51-client.txt](https://github.com/IMB11/SkinShuffle/files/13782588/crash-2023-12-28_12.40.51-client.txt)

<details>
<summary>Crash report </summary>

````

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-12-28 12:40:51
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "$$0" is null
	at net.minecraft.class_1297.method_5739(class_1297.java:1573)
	at com.provismet.provihealth.config.Options.shouldRenderHealthFor(Options.java:96)
	at com.provismet.provihealth.world.EntityHealthBar.render(EntityHealthBar.java:48)
	at net.minecraft.class_897.handler$zlf000$provihealth$addHealthBar(class_897.java:529)
	at net.minecraft.class_897.method_3936(class_897.java)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_1007.method_4215(class_1007.java:67)
	at net.minecraft.class_1007.method_3936(class_1007.java:44)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:82)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:54)
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:82)
	at net.minecraft.class_437.method_25394(class_437.java:121)
	at net.minecraft.class_442.method_25394(class_442.java:294)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1297.method_5739(class_1297.java:1573)
	at com.provismet.provihealth.config.Options.shouldRenderHealthFor(Options.java:96)
	at com.provismet.provihealth.world.EntityHealthBar.render(EntityHealthBar.java:48)
	at net.minecraft.class_897.handler$zlf000$provihealth$addHealthBar(class_897.java:529)
	at net.minecraft.class_897.method_3936(class_897.java)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_1007.method_4215(class_1007.java:67)
	at net.minecraft.class_1007.method_3936(class_1007.java:44)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:82)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:54)
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:82)
	at net.minecraft.class_437.method_25394(class_437.java:121)
	at net.minecraft.class_442.method_25394(class_442.java:294)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (com.mineblock11.skinshuffle.client.gui.cursed.DummyClientPlayerEntity)
	Entity ID: 2
	Entity Name: Anon
	Entity's Exact location: 8.50, 65.00, 8.50
	Entity's Block location: World: (8,65,8), Section: (at 8,1,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:82)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:54)
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:82)
	at net.minecraft.class_437.method_25394(class_437.java:121)
	at net.minecraft.class_442.method_25394(class_442.java:294)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@522b680d
	Location: 0.00,0.00,0.00 - World: (0,0,0), (Error finding chunk loc), (Error finding world loc)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:82)
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:54)
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:82)
	at net.minecraft.class_437.method_25394(class_437.java:121)
	at net.minecraft.class_442.method_25394(class_442.java:294)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_442
	Mouse location: Scaled: (0, 0). Absolute: (0.000000, 0.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2488)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 207577456 bytes (197 MiB) / 538968064 bytes (514 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2121
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16887.90
	Virtual memory used (MB): 14667.19
	Swap memory total (MB): 8945.78
	Swap memory used (MB): 1402.44
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.91.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.78+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.8+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+95a8ac51a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.11+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.9+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.44+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.12+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		provihealth: Provi's Health Bars 1.2.2+1.20.2
			lilylib: LilyLib 1.0.0+1.20
		skinshuffle: SkinShuffle 1.0.2+1.20.2
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			org_mineskin_java-client: java-client 1.2.4-SNAPSHOT
			spruceui: SpruceUI 5.0.3+1.20.2
			yet_another_config_lib_v3: YetAnotherConfigLib 3.3.0-beta.1+1.20.2
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
	JVM uptime in seconds: 43.429
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 31.0.101.2121, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_AU
	CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

````

</details>

### Log

[latest.log](https://github.com/IMB11/SkinShuffle/files/13782592/latest.log)

<details>
<summary>Log </summary>

````

[12:40:10] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.3
[12:40:10] [main/WARN]: Warnings were found!
 - Mod 'Provi's Health Bars' (provihealth) 1.2.2+1.20.2 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Provi's Health Bars' (provihealth) 1.2.2+1.20.2 recommends any version of cloth-config, which is missing!
	 - You should install any version of cloth-config for the optimal experience.
[12:40:10] [main/INFO]: Loading 71 mods:
	- fabric-api 0.91.2+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.78+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.8+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.2+95a8ac51a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.11+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.9+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.44+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.12+4944b5a5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.2
	- provihealth 1.2.2+1.20.2
	   \-- lilylib 1.0.0+1.20
	- skinshuffle 1.0.2+1.20.2
	   |-- com_konghq_unirest-java_standalone 3.11.9
	   |-- commons-validator_commons-validator 1.7
	   |-- org_jsoup_jsoup 1.16.1
	   |-- org_mineskin_java-client 1.2.4-SNAPSHOT
	   |-- spruceui 5.0.3+1.20.2
	   \-- yet_another_config_lib_v3 3.3.0-beta.1+1.20.2
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
[12:40:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/anon/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:40:11] [main/INFO]: Compatibility level set to JAVA_16
[12:40:11] [main/INFO]: Compatibility level set to JAVA_17
[12:40:13] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[12:40:15] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[12:40:29] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 399 milliseconds
[12:40:34] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[12:40:35] [Render thread/INFO]: Setting user: Anon
[12:40:36] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[12:40:36] [Render thread/INFO]: Loading SkinShuffleConfig...
[12:40:36] [Render thread/INFO]: Saving SkinShuffleConfig...
[12:40:37] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[12:40:39] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, lilylib, provihealth, skinshuffle, spruceui, yet_another_config_lib_v3)
[12:40:39] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[12:40:43] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[12:40:43] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[12:40:44] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (Galaxy Buds2 (F23E))
[12:40:44] [Render thread/INFO]: Sound engine started
[12:40:44] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[12:40:44] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[12:40:44] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[12:40:44] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[12:40:44] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[12:40:44] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[12:40:44] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[12:40:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[12:40:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[12:40:46] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[12:40:47] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[12:40:47] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[12:40:47] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:40:47] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[12:40:49] [Render thread/INFO]: Set player skin: http://textures.minecraft.net/texture/289f18fd2e2356ad7e89e4f2bf4f7d438bd286d4e71e894408a0adb8290a33b6
[12:40:51] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_23317()" because "$$0" is null
	at net.minecraft.class_1297.method_5739(class_1297.java:1573) ~[client-intermediary.jar:?]
	at com.provismet.provihealth.config.Options.shouldRenderHealthFor(Options.java:96) ~[provihealth-1.2.2+1.20.2.jar:?]
	at com.provismet.provihealth.world.EntityHealthBar.render(EntityHealthBar.java:48) ~[provihealth-1.2.2+1.20.2.jar:?]
	at net.minecraft.class_897.handler$zlf000$provihealth$addHealthBar(class_897.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_897.method_3936(class_897.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:146) ~[client-intermediary.jar:?]
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:82) ~[SkinShuffle-1.0.2+1.20.2.jar:?]
	at com.mineblock11.skinshuffle.client.gui.cursed.GuiEntityRenderer.drawEntity(GuiEntityRenderer.java:54) ~[SkinShuffle-1.0.2+1.20.2.jar:?]
	at com.mineblock11.skinshuffle.client.gui.widgets.OpenCarouselButton.method_25394(OpenCarouselButton.java:82) ~[SkinShuffle-1.0.2+1.20.2.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25394(class_442.java:294) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 9 more

````

</details>

saw this in the wild at https://www.reddit.com/r/fabricmc/comments/18s397x/back_at_it_again/

**Comment by Aulberon** [comment]
I´m pretty sure it also happens with this mod:
https://modrinth.com/mod/tslatentitystatus

**Comment by arcade-smasher** [comment]
It's also incompatible with Wildfire's Female Gender mod:
https://modrinth.com/mod/female-gender

**Comment by IMB11** [comment]
@Aulberon Will push a fix for TSL alongside this.
